In [1]:
import torch

In [2]:
torch.__version__

'2.3.1+cu121'

In [3]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
#Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

# Random Tensors

In [15]:
# Creating a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.9412, 0.8391, 0.4092, 0.1582],
        [0.5855, 0.9002, 0.2603, 0.8201],
        [0.4348, 0.3540, 0.5054, 0.5873]])

In [16]:
random_tensor.dtype

torch.float32

In [17]:
# Creating a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

# Zeroes and Ones

In [18]:
zeroes = torch.zeros(size=(3, 4))
zeroes

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [20]:
zeroes.dtype
ones.dtype

torch.float32

## Creating a Range in Tensors

In [21]:
zero_to_ten = torch.arange(start=1, end=11)
zero_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
eleven_to_twenty = torch.arange(11, 21)
eleven_to_twenty

tensor([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [23]:
zero_to_hundred = torch.arange(start=0, end=100, step=9)
zero_to_hundred

tensor([ 0,  9, 18, 27, 36, 45, 54, 63, 72, 81, 90, 99])

In [24]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [25]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [26]:
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.])

In [27]:
int_32_tensor = float_32_tensor.type(torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [28]:
float_16_tensor * int_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

# Basic Operations

In [29]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [30]:
tensor - 10

tensor([-9, -8, -7])

In [31]:
tensor.multiply(10)

tensor([10, 20, 30])

In [32]:
tensor * 10

tensor([10, 20, 30])

## Matrix Multiplication

PyTorch implements matrix multiplication functionality in the torch.matmul() method.

The main two rules for matrix multiplication to remember are:

The inner dimensions must match:
1. `(3, 2) @ (3, 2)` won't work
2. `(2, 3) @ (3, 2)` will work
3. `(3, 2) @ (2, 3)` will work

The resulting matrix has the shape of the outer dimensions:
1. `(2, 3) @ (3, 2)` -> `(2, 2)`
2. `(3, 2) @ (2, 3)` -> `(3, 3)`

Note: "`@`" in Python is the symbol for matrix multiplication

In [33]:
tensor

tensor([1, 2, 3])

In [34]:
tensor * tensor

tensor([1, 4, 9])

In [35]:
torch.matmul(tensor, tensor)

tensor(14)

In [36]:
tensor @ tensor

tensor(14)

In [37]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 8],
                         [9, 10],
                        [11, 12]])

In [38]:
# It throws error because the shape of these two matrix cannot be multiplied

torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [39]:
# In such cases sometimes, we can transpose a matrix

tensor_B.T

tensor([[ 7,  9, 11],
        [ 8, 10, 12]])

In [40]:
tensor_B.T.shape

torch.Size([2, 3])

In [41]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

# Finding the min, max, mean, sum, etc

In [42]:
x = torch.arange(0, 100, 9)
x

tensor([ 0,  9, 18, 27, 36, 45, 54, 63, 72, 81, 90, 99])

In [43]:
x.min()

tensor(0)

In [44]:
x.max()

tensor(99)

In [45]:
x.type(torch.float32).mean()

tensor(49.5000)

In [46]:
x.sum()

tensor(594)

### Positional min/max (argmin/argmax)

In [47]:
import torch

In [48]:
tensor = torch.arange(10, 100, 10)
tensor

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [49]:
tensor.argmax()

tensor(8)

In [50]:
tensor.argmin()

tensor(0)

In [51]:
X = torch.arange(1., 8.)
X

tensor([1., 2., 3., 4., 5., 6., 7.])

In [52]:
X.shape

torch.Size([7])

In [53]:
X_reshaped = X.reshape(1, 7)
X_reshaped, X_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [54]:
Z = X.view(1, 7)
Z, Z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [55]:
X

tensor([1., 2., 3., 4., 5., 6., 7.])

In [56]:
Z[:, 0] = 5
Z

tensor([[5., 2., 3., 4., 5., 6., 7.]])

So changing the view changes the original tensor too.

In [57]:
X

tensor([5., 2., 3., 4., 5., 6., 7.])


If we wanted to stack our new tensor on top of itself five times, we could do so with `torch.stack()`.

In [58]:
X_stacked = torch.stack([X, X, X, X, X], dim=0)
X_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

In [59]:
X_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7.]])

In [60]:
X_reshaped.shape

torch.Size([1, 7])

In [61]:
X_squeezed = X_reshaped.squeeze()
X_squeezed

tensor([5., 2., 3., 4., 5., 6., 7.])

In [62]:
X_squeezed.shape

torch.Size([7])

You can also rearrange the order of axes values with `torch.permute(input, dims)`, where the `input` gets turned into a view with new `dims`.

In [63]:
x_original = torch.rand(size=(224, 224, 3))

x_permuted = x_original.permute(2, 0, 1)

print(f"Previous shape: {x_original.shape}")
print(f"New Shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New Shape: torch.Size([3, 224, 224])


# Pytorch tensors and numpy

In [64]:
import numpy as np

In [65]:
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [66]:
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [67]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [68]:
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [69]:
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Random Tensor A: \n{random_tensor_A}")
print(f"Random Tensor B: \n{random_tensor_B}")

Random Tensor A: 
tensor([[0.8072, 0.1372, 0.4678, 0.5855],
        [0.7374, 0.1629, 0.9878, 0.4621],
        [0.6078, 0.3990, 0.0659, 0.4451]])
Random Tensor B: 
tensor([[0.7657, 0.0785, 0.5686, 0.9139],
        [0.0617, 0.4484, 0.9236, 0.0287],
        [0.2451, 0.9630, 0.7091, 0.3269]])


In [70]:
import random

RANDOM_SEED = 42

torch.manual_seed(seed = RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(seed = RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(f"Random Tensor C: \n{random_tensor_C}")
print(f"Random Tensor D: \n{random_tensor_D}")

random_tensor_C == random_tensor_D

Random Tensor C: 
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
Random Tensor D: 
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

# Running Tensors  on GPU

In [71]:
!nvidia-smi

Fri Jul 19 04:39:54 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   56C    P8              12W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [72]:
import torch
torch.cuda.is_available()

True

In [73]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [74]:
torch.cuda.device_count()

1

In [75]:
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to  GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

In [76]:
# if tensor is on gpu, can't transform it to NumPy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [77]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [78]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')