<a href="https://colab.research.google.com/github/ArmaanMistry/pytorch-learning/blob/main/02_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch Fundamentals Exercises

### 1. Documentation reading

  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



### 2. Create a random tensor with shape `(7, 7)`.


In [ ]:
# Import torch
import torch

# Create random tensor
random_tensor = torch.rand(7, 7)
random_tensor

tensor([[0.4214, 0.7146, 0.2650, 0.7488, 0.0080, 0.3871, 0.1571],
        [0.2274, 0.8196, 0.4083, 0.0911, 0.7311, 0.4793, 0.9369],
        [0.1079, 0.4927, 0.0119, 0.8976, 0.0624, 0.4505, 0.3003],
        [0.6632, 0.2073, 0.2614, 0.5598, 0.3739, 0.9755, 0.6187],
        [0.9733, 0.6242, 0.0115, 0.6159, 0.8457, 0.0060, 0.2833],
        [0.8230, 0.2275, 0.9569, 0.8297, 0.5323, 0.2119, 0.0169],
        [0.9534, 0.0539, 0.5485, 0.2144, 0.6964, 0.0609, 0.1142]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [ ]:
# Create another random tensor
random_tensor_B = torch.rand(1, 7)

# Perform matrix multiplication
random_tensor.matmul(random_tensor_B.T)

tensor([[1.0114],
        [1.8400],
        [0.9682],
        [1.4309],
        [1.2582],
        [1.7164],
        [1.1337]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [ ]:
import random

# Set manual seed
RANDOM_SEED = 0

# Create two random tensors
torch.manual_seed(RANDOM_SEED)
random_tensor_A = torch.rand(7, 7)

random_tensor_B = torch.rand(1, 7)

# Matrix multiply tensors
random_tensor_A.matmul(random_tensor_B.T)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [ ]:
import torch
import random

# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f"Device: {device}")

# Create two random tensors on GPU
tensor_A = torch.rand(2, 3).to(device)
tensor_B = torch.rand(2, 3).to(device)

tensor_A, tensor_B

Device: cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
# Perform matmul on tensor_A and tensor_B
tensor_A_mul_B = tensor_A.matmul(tensor_B.T)

### 8. Find the maximum and minimum values of the output of 7.

In [ ]:
# Find max
max = tensor_A_mul_B.max()

# Find min
min = tensor_A_mul_B.min()

max, min

(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
# Find arg max
argmax = tensor_A_mul_B.argmax()

# Find arg min
argmin = tensor_A_mul_B.argmin()

argmax, argmin

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
# Set seed
RANDOM_SEED = 7
torch.manual_seed(RANDOM_SEED)

# Create random tensor
random_tensor_C = torch.rand(1, 1, 1, 10)

# Remove single dimensions
random_tensor_D = random_tensor_C.squeeze()

# Print out tensors and their shapes
print(f"{random_tensor_C, random_tensor_C.shape}")
print(f"{random_tensor_D, random_tensor_D.shape}")

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]), torch.Size([1, 1, 1, 10]))
(tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]), torch.Size([10]))
